# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Journey' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Journey
	pod 'Alamofire', '~> 5.4'
	pod 'Moya', '~> 14.0'
	pod 'SwiftLint'
	pod 'lottie-ios'
	pod 'Firebase/Analytics'
	pod 'Firebase/Messaging'
	pod 'IQKeyboardManagerSwift'
end
